openapi: 3.1.0
info:
  title: Dish and Ingredient API
  description: OpenAPI specification for managing ingredients and dishes
  version: 1.0.0

servers:
  - url: 'http://localhost:8080'

paths:
  '/ingredient':
    get:
      responses:
        '200':
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
  '/ingredient/{id}':
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ingredient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                exemple: "Ingredient.id={id} is not found"

  '/ingredient/{id}/stock':
    get:
      summary: Retrieve ingredient stock at a given time
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: at
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: unit
          in: query
          required: true
          schema:
            type: string
            enum: [PCS,KG,L]
      responses:
        '200':
          description: Stock value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'

        '400':
          description: Missing query parameters
          content:
            text/plain:
              schema:
                type : string
                exemple : "Either mandatory query parameter at or unit is not provided."
        '404':
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                exemple: "Ingredient.id={id} is not found"
  '/dishes':
    get:
      responses:
        '200':
          description: List of dishes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'

  '/dishes/{id}/ingredients':
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Ingredient'
      responses:
        '200':
          description: Ingredient updated
        '400':
          description: Missing request body
          content:
            text/plain:
              schema:
                type: string
                exemple: "Request body is required"
        '404':
          description: Dish not found
          content:
            text/plain:
              schema:
                type: string
                exemple: "Dish.id={id} is not found"


components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
        price:
          type: number

    Stock:
      type: object
      properties:
        unit:
          type: string
          enum: [PCS, KG, L]
        value:
          type: number

    Dish:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
